export const roleList = [
  "Developer",
  "Designer",
  "Product Manager",
  "Project Manager",
  "Team Lead",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Data Analyst",
  "Data Scientist",
  "Business Analyst",
  "Marketing Manager",
  "Sales Manager",
  "HR Manager",
  "Finance Manager",
  "Operations Manager",
  "CEO",
  "CTO",
  "CIO",
  "Consultant",
  "Freelancer",
  "Student",
  "Intern",
  "Other"
];

export const industryTypesList = [
  "Education",
  "Technology",
  "Healthcare",
  "Finance",
  "Banking",
  "Insurance",
  "Real Estate",
  "Manufacturing",
  "Retail",
  "E-commerce",
  "Hospitality",
  "Tourism",
  "Transportation",
  "Logistics",
  "Construction",
  "Energy",
  "Utilities",
  "Telecommunications",
  "Media",
  "Entertainment",
  "Gaming",
  "Sports",
  "Food & Beverage",
  "Agriculture",
  "Automotive",
  "Aerospace",
  "Defense",
  "Government",
  "Non-profit",
  "Consulting",
  "Legal",
  "Marketing",
  "Advertising",
  "Public Relations",
  "Human Resources",
  "Recruitment",
  "Research",
  "Pharmaceuticals",
  "Biotechnology",
  "Environmental",
  "Fashion",
  "Beauty",
  "Fitness",
  "Other"
];
